### ISSUE TITLE
Document or remove dependency on styled-components

### ISSUE THREAD

**Issue by grrowl** [FormidableLabs/react-ssr-prepass#13]
We should add explanation of why the requirement on styled-components exists. In my project, I use `@emotion/styled`, so I get a warning emitted on compilation in dev

```
[ warn ]  ./node_modules/react-ssr-prepass/dist/react-ssr-prepass.development.js
Module not found: Can't resolve 'styled-components' in '/Users/tom/Documents/projects/holy-rabbit/app/node_modules/react-ssr-prepass/dist'
[ info ]  ready on http://localhost:3000
```

**Comment by kitten** [comment]
Sorry, I did forget to add the dependency. That being said, you can just stub out styled-components in Webpack as an empty module and it’ll just skip the optimisation.

I’ll probably refine how this works in the future

**Comment by jasonlor** [comment]
+1 Also seeing this!

**Comment by rtsao** [comment]
FWIW I have a published [fork](https://github.com/rtsao/react-ssr-prepass) with this optimization removed entirely: https://github.com/FormidableLabs/react-ssr-prepass/compare/master...rtsao:master 

https://www.npmjs.com/package/@rtsao/react-ssr-prepass

I wasn't sure how best to resolve this upstream without removing the functionality entirely. Perhaps something with `__non_webpack_require__`?

**Comment by kitten** [comment]
I'm still thinking how to resolve this properly, but this might require some API changes and a major bump, so I'll update this issue shortly.
