### ISSUE TITLE
Basic Usage?

### ISSUE THREAD

**Issue by ll-aashwin-ll** [FormidableLabs/react-ssr-prepass#14]
I'm having trouble with basic usage of this library, on the server I have:

```jsx
  const renderApp = async App => {
    const element = createElement(App)
    await ssrPrepass(element)


    return renderToString(element)
  }

    const App = () => (
      <Provider store={store}>
        <StaticRouter location={req.url} context={ctx}>
          <GlobalStyle />
          <Route component={Index} />
        </StaticRouter>
      </Provider>
    );

    const markup = await renderApp(App);
```

With the debugger I see that it waits for the promises thrown under Suspense and the redux store is correctly populated after waiting for prepass. But when it tries to `renderToString(element)` I get the error:

`Error: ReactDOMServer does not yet support Suspense.`

Is this not the correct usage? I couldn't any other examples of it's usage. 

Thanks.

**Comment by ll-aashwin-ll** [comment]
So I was under the impression from reading the docs that thrown promises would have to be under React's `<Suspense ...>` tag. Omitting this, the app works. If this is indeed the case, this issue can be closed.

**Comment by kitten** [comment]
You can't use the `Suspense` element with `react`'s server-side renderer. You can use it with `react-ssr-prepass`, but it's a noop. Hence it only makes sense to use it on the client-side. So on the server you'll likely want to not use the `Suspense` element at all
