### ISSUE TITLE
[Question] Are portals supported?

### ISSUE THREAD

**Issue by sgb-io** [FormidableLabs/react-ssr-prepass#24]
Should this library support rendering content inside portals?

I can see that [there is a test ](https://github.com/FormidableLabs/react-ssr-prepass/blob/6510fdfa869283101222e411ea3555e6b4429156/src/__tests__/visitor.test.js#L217)that hints maybe not. Is this by design, or not possible, or some limitation?

**Comment by kitten** [comment]
Sorry for the late reply! Portals aren’t supported. Like SSR in react-dom itself it’s left out, so if you have multiple sub trees that you’re later stitching together with portals then you’ll have to run prepaid on each sub tree individually :)

If I’m missing something crucial here however, please let me know! I don’t use portals very frequently so maybe I’m just not familiar with a nuance of them and SSR.

**Comment by sgb-io** [comment]
Closing as intentions clarified
