### ISSUE TITLE
Implementation with Next.js

### ISSUE THREAD

**Issue by renanmav** [FormidableLabs/react-ssr-prepass#26]
Hi guys.

How would I implement `react-srr-prepass` on a Next.js app?

**Comment by kitten** [comment]
You can find an example over on the `urql` repository 👍  It basically comes down to using `AppTree` manually, but there are some minor variations on this based on whether you'll use it on a page or `_document` level https://github.com/FormidableLabs/urql/blob/94bb645808cec9e210bceec438621df101f48bd4/examples/3-ssr-with-nextjs/src/with-urql-client.js#L33-L41
