### ISSUE TITLE
Relationship to more "full-featured" SSR libraries?

### ISSUE THREAD

**Issue by earksiinni** [FormidableLabs/react-ssr-prepass#58]
I use `react-ssr-prepass` for SSR with urql.

Separately, I'm assessing how to implement code-splitting with Suspense across my app. I've never done it before and also I'm new to working with Suspense. React's docs recommend using [Loadable Components](https://loadable-components.com).

Is this library "compatible" with something like Loadable Components? Can they be used side-by-side? How do they relate to each other?

Sorry for this n00b question. Please feel free to explain to me like I'm a five-year old (software engineer 🙂).

**Comment by kitten** [comment]
Hiya 👋

Sorry, I must've missed your question! Loadable Components is a good choice! You may not even need this library for it. What you're looking for is:

- synchronous imports on the server, async on the client (via transpilation)
- being able to list which components where loaded and populating preloads for the client so it has the right components preloaded for rehydration
