### ISSUE TITLE
React 17 support

### ISSUE THREAD

**Issue by LarsJK** [FormidableLabs/react-ssr-prepass#62]
I'm unable to install new next-urql in a next.js project because react-ssr-prepass has a peer dip on react ^16.8.0

```
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8.0" from react-ssr-prepass@1.2.1
npm ERR! node_modules/next-urql/node_modules/react-ssr-prepass
npm ERR!   react-ssr-prepass@"^1.2.1" from next-urql@3.0.0
npm ERR!   node_modules/next-urql
npm ERR!     next-urql@"*" from the root project
```

**Comment by kitten** [comment]
This should now be fixed in the React v17 release of `react-ssr-prepass@1.3.0`, so if you bump a minor this should be resolved: https://github.com/FormidableLabs/react-ssr-prepass/releases/tag/v1.3.0
