### ISSUE TITLE
Provide ESM build

### ISSUE THREAD

**Issue by frandiox** [FormidableLabs/react-ssr-prepass#65]
Hello, thanks for this package! Finally possible to make easy SSR with react.
I'm using this in [`vite-ssr`](https://github.com/frandiox/vite-ssr) and [`vitedge`](https://github.com/frandiox/vitedge), which basically do SSR with Vite and React/Vue in Node or Cloudflare Workers.

Vite tends to complain about packages that don't provide an ESM build, and it requires some manual setup to make it work.
It would be great if `react-ssr-prepass` exported an ESM build directly instead of only CJS.

Thanks!

**Comment by kitten** [comment]
Published in 1.4.0
