### ISSUE TITLE
Compatible with apollo@3 hooks ?

### ISSUE THREAD

**Issue by Ziker22** [FormidableLabs/react-ssr-prepass#67]
Hello im trying to make prepass work with apollo 3(useQuery hook) together with nextjs
I took this from docs
```
ssrPrepass(<App />, (element, instance) => {
 if (instance && instance.fetchData) {
    return instance.fetchData()
  }
})
```

My problem is since im using hooks instances of my components doesnt seem to have `fetchData` property
Is there any chance i can check different condition ? Or should i switch to apollos `Query` component ? Or theres no way to make this work ?

Any advice will be highly appreciated :)

**Comment by bregenspan** [comment]
@Ziker22 based on https://github.com/FormidableLabs/react-ssr-prepass/pull/61/commits/e04b17b942b635566e496e800da1885558724f04 and my own attempts to reconcile Apollo 3 + react-prepass, I believe that there's no longer a supported answer for this, regardless of whether you use the Hooks-based approach or Query components.

(I'd also love to hear if anyone has figured out a decent workaround for react-ssr-prepass Apollo 3 compat.)

**Comment by kitten** [comment]
Well, Apollo doesn't support Suspense as far as I know, especially suspense during SSR is what `react-ssr-prepass` would need it to work, so unfortunately all the old docs sections (that were removed) for react-apollo v2 don't apply anymore
