### ISSUE TITLE
Example with vite-plugin-ssr

### ISSUE THREAD

**Issue by brillout** [FormidableLabs/react-ssr-prepass#73]
Author of [vite-plugin-ssr](https://vite-plugin-ssr.com/) here. Many of my users are using `react-ssr-prepass`; an example showcasing the plugin + `react-ssr-prepass` would be lovely for both our users.

Thoughts?

**Comment by JoviDeCroock** [comment]
Hey @brillout I've quickly thrown together an example using urql https://github.com/JoviDeCroock/vite-ssr-prepass-example running into an issue where prepass throws an error where it can't find React currently (from esbuild) 😅

**Comment by brillout** [comment]
Just saw that, neat love it 👌.

**Comment by JoviDeCroock** [comment]
@brillout does this suffice to show the gist of it? It basically shows how we can leverage it to resolve data suspense boundaries which are for instance used in urql, there are other appliances like going through the tree and calling methods that are defined on components 😅 but I think this shows the gist of it

**Comment by brillout** [comment]
Perfect.

https://vite-plugin-ssr.com/urql
https://github.com/brillout/vite-plugin-ssr/tree/master/examples/urql/

Let me know if you want me to PR a little section "Vite" with the above links to https://formidable.com/open-source/urql/docs/advanced/server-side-rendering/#vue-suspense

I'll maintain the urql example for the foreseeable future.

Love our tools combo :-).
