### ISSUE TITLE
Usage of secret internals breaks compatibility with Preact

### ISSUE THREAD

**Issue by LukasBombach** [FormidableLabs/react-ssr-prepass#8]
I am not sure if you intend to be compatible with `Preact` but you are using 

```js
React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED
```

which breaks compatibility with `Preact`. This also means `Preact` cannot be used with `Next` (at least not `Preact X`, since there is no equivalent for this.

**Comment by StoneCypher** [comment]
The name is an indication of whether the React team thinks this should be externally usable

**Comment by kitten** [comment]
Sorry for the late reply, this package is definitely not meant to be used with `preact`, since it's a simple React renderer, so it won't work with any compat package

**Comment by marvinhagemeister** [comment]
For those stumbling on this issue: @sventschui did a port of it to preact you can drop in via an alias. Check out https://github.com/sventschui/preact-ssr-prepass :tada:
