### ISSUE TITLE
why HTML node showing empty or undefined?

### ISSUE THREAD

**Issue by naveennsit** [FormidableLabs/react-ssr-prepass#83]
I am checking this code to render react component on SSR
https://github.com/htdangkhoa/react-ssr-starter.

deployed latest code https://reactssrstarter.herokuapp.com/home

When I check source code HTML is not generated or In other words react component is not rendered on server

I try to debug issue below `node` coming `undefined` don't know why ?
  

    const node = await ssrPrepass(
        <ChunkExtractorManager extractor={extractor}>
          <Provider store={store}>
            <StaticRouter location={req.url}>
              <HelmetProvider context={helmetContext}>
                <App />
              </HelmetProvider>
            </StaticRouter>
          </Provider>
        </ChunkExtractorManager>,
      );
    
      const markup = renderToString(node);

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/V1glN.png

any idea ? ?

**Comment by kitten** [comment]
Please check the types and docs :v:

Prepass does not return React elements and hence your `const node` variable is being set to `undefined`: https://github.com/FormidableLabs/react-ssr-prepass/blob/099119761074dc35d2bc0d884297e6c84c77f684/src/index.js#L61
